name: flutters

environment:
  sdk: ^3.10.7

workspace:
  - packages/gmana
  - packages/gmana_extensions
  - packages/gmana_flutter_extensions
  - packages/gmana_form
  - packages/gmana_flutter
  - packages/gmana_functional
  - packages/gmana_lints
  - packages/gmana_predicates
  - packages/gmana_spinner
  - packages/gmana_spinner/example
  - packages/gmana_utils
  - packages/gmana_validation
  - packages/gmana_value_objects
  - packages/gmana_form/example
  - packages/gmana_flutter_extensions/example
  - packages/gmana_flutter/example
