name: gmana_spinner
description: Flutter loading spinner widgets for the Gmana ecosystem.
version: 0.0.1
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_spinner
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_spinner
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - flutter
  - spinner
  - loading
  - widgets

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  gmana_lints: ^0.1.0
