name: gmana_flutter
description: A comprehensive Flutter UI library providing curated widgets, form helpers, theme services, and extensions to accelerate and standardize development.
version: 0.0.10
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_flutter
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_flutter
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - flutter
  - ui
  - widgets
  - form
  - utilities

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  gmana: ^0.2.0
  gmana_flutter_extensions: ^0.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  gmana_lints: ^0.1.0
