name: gmana_flutter
description: A comprehensive Flutter UI library providing curated widgets, form helpers, theme services, and extensions to accelerate and standardize development.
version: 0.0.8
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_flutter
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_flutter
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - flutter
  - ui
  - widgets
  - form
  - utilities

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  gmana: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
