name: gmana_utils
description: Pure Dart runtime utilities and Result extensions for resilient asynchronous workflows.
version: 0.0.1
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_utils
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - utility
  - debounce
  - throttle
  - id-generator
  - result

environment:
  sdk: ^3.7.2

dev_dependencies:
  gmana_lints: ^0.1.0
  lints: ^6.0.0
  test: ^1.30.0

resolution: workspace
