name: gmana
description: Convenience facade re-exporting gmana_functional, gmana_predicates, gmana_validation, gmana_utils, and gmana_extensions.
version: 0.2.0
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - extensions
  - utility
  - validator
  - functional-programming

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  gmana_extensions: ^0.0.2
  gmana_functional: ^0.0.1
  gmana_predicates: ^0.0.1
  gmana_utils: ^0.0.1
  gmana_validation: ^0.0.1

dev_dependencies:
  gmana_lints: ^0.1.0
  lints: ^6.0.0
  test: ^1.30.0
