name: gmana
description: A core Dart utility package providing extensions, validation utilities, and functional programming constructs for consistent development.
version: 0.2.0
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - extensions
  - utility
  - validator
  - functional-programming

environment:
  sdk: ^3.7.2

resolution: workspace

# dependencies:

dev_dependencies:
  test: ^1.30.0
  lints: ^6.0.0
