name: gmana_extensions
description: Dart extension methods for Duration, String, num, Stream, Iterable, and validation utilities.
version: 0.0.2
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_extensions
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - dart
  - extensions
  - utilities

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  gmana_predicates: ^0.0.1
  gmana_validation: ^0.0.1

dev_dependencies:
  gmana_lints: ^0.1.0
  lints: ^6.1.0
  test: ^1.30.0
