name: gmana_value_objects
description: Production-ready value objects with configurable validation for Email, Password, Text, and Number
version: 0.0.4
repository: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_value_objects
homepage: https://github.com/sun-sreng/flutters/tree/main/packages/gmana_value_objects
issue_tracker: https://github.com/sun-sreng/flutters/issues

topics:
  - validation
  - domain-driven-design
  - ddd
  - utility

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  gmana: ^0.2.0
  meta: ^1.17.0

dev_dependencies:
  test: ^1.30.0
  lints: ^6.1.0
